# Generated by Django 2.2.5 on 2019-09-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='self_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
